### ISSUE TITLE
Can't find Source Code on Webkit when Downloading from Google Git

### ISSUE THREAD

**Issue by ev1stensberg** [ChromeDevTools/devtools-frontend#10]
I've been setting up my repo from [this guide](https://docs.google.com/document/d/1WNF-KqRSzPLUUfZqQG5AFeU_Ll8TfWYcJasa_XGf7ro/view#) but when navigating to `Webkit/Source` there's nothing there but tests. Cloned this repo, while trying to run `npm run closure` but it fails due that it doesn't find the webkit source code within this repo, as it is not included ( ? ). 

### Webkit Source Code from the Google Docs after install
</hr>

![skjermbilde 2017-01-25 kl 21 46 27](https://cloud.githubusercontent.com/assets/16735925/22308560/c27bc5a2-e347-11e6-8cb5-dc51a4992753.png)

### `npm run closure`

![skjermbilde 2017-01-25 kl 21 47 40](https://cloud.githubusercontent.com/assets/16735925/22308597/eeaa9a4a-e347-11e6-956f-98ecffb79e1e.png)

_Array and path is my own work, trying to figure out the issue_

**Comment by ev1stensberg** [comment]
Also getting exceptions/errors when running `npm run start`, may due that it doesn't find the modules it's looking for, like in this issue

**Comment by wwwillchen** [comment]
It looks like your full clone of chromium/src didn't succeed. Can you try again? It's a big git repo so maybe there was some network issue the first time.

Unfortunately you can't run closure with just the front-end checkout (this repo) because it needs metadata that's outside of this git subtree (i.e. the *_protocol.json files which describe the protocol to talk to the C++ back-end). In short, while it's nice to hack around on DevTools with repo it's difficult to be fully productive (e.g. run closure, run tests, and upload patches) without the full checkout.

**Comment by ev1stensberg** [comment]
@wwwillchen That's related to running `npm run start`, right? 

</hr> 

Anyway to run `closure` with the build intact?

**Comment by ev1stensberg** [comment]
@wwwillchen Fixed it! Looking forward to contributing!

**Comment by ev1stensberg** [comment]
@wwwillchen https://codereview.chromium.org/2656343003/
